# SSH settings
server_host: "xxx.xxx.xxx.xxx" # IP address of your server here
server_user_name: "xxxxx" # Linux user to run test node
ssh_key_file_path: "your_key_path_here" # Example: "~/.ssh/id_rsa.pem"

# Linux user settings to run testnode
node_user_name: "test_user"  
node_user_group: "test_user" 

# node settings
docker_compose_version: 1.27.4 # Please check https://docs.docker.com/compose/release-notes/ 
network_type: "mainnet"
node_type: "dual"
node_friendlyName: "your_node_name_here" # Node name
signing_privateKey: "" # Your Private key or keep here empty to generate new privateKey
vrf_signing_privateKey: "" # Keep here empty to generate new privateKey.
encryption_password: # Password and Preset encryption password.

# swap file size
swap_file_size_mb: '4096'

# # Fill below if you want your site to be https
# letsencrypt_email: "youremailaddress@example.com" # To receive email from let's encrypt
# domain_name: "example.com" # Domain name to be https