  all:
    hosts:
      default_server:
        ansible_host: "{{ server_host }}"
        ansible_user: "{{ server_user_name }}"
        ansible_ssh_private_key_file: "{{ ssh_key_file_path }}"
        # Define python ssh module
        ansible_connection: paramiko
    vars:
      ansible_python_interpreter: /usr/bin/python3